:modules:
#    - hammer_cli_foreman
#    - hammer_cli_katello

:foreman:
  :host: 'https://localhost/'
  :username: 'admin'
  :password: 'changeme'


:ui:
  :interactive: true
  :per_page: 20
  :history_file: '~/.foreman/history'


# enable/disable color output of logger in Clamp commands
:watch_plain: false

:log_dir: '~/.foreman/log'
:log_level: 'error'
:log_api_calls: false
#:log_owner: 'foreman'
#:log_group: 'foreman'
#:log_size: 5 #MB
