# User interface related settings
:ui:
  # Enable interactive queries?
  :interactive: true
  # Number of records listed per page
  # :per_page: 20
  # Location of shell history file
  :history_file: '~/.hammer/history'
  # Mark translated strings with X characters (for developers)
  #:mark_translated: false
  # Hide headers from output of list actions
  # :no_headers: true

# Enable/disable color output of logger in Clamp commands
:watch_plain: false

# Forece relaod of Apipie cache with every Hammer invocation
:reload_cache: false

# Directory where the logs are stored. The default is /var/log/hammer/ and the log file is named hammer.log
:log_dir: '~/.hammer/log'

# Logging level. One of debug, info, warning, error, fatal
:log_level: 'error'

#:log_owner: 'foreman'
#:log_group: 'foreman'

# Maximum log size in bytes. Log rotates when the value gets exceeded
#:log_size: 5 #in MB

# Log record pattern (logging gem syntax)
#:log_pattern: '[%5l %d %c] %m'


# SSL auth options
#:ssl:
  # Path to a CA file in PEM format, mutually exclusive with :ssl_ca_path:
  #:ssl_ca_file: '/path/to/ca_certificate.pem'

  # Path to a direcotry with CA files, mutually exclusive with :ssl_ca_file:
  # The directory should contain one certificate per file in PEM format, with a file name of the form hash.N
  # The hash can be obtained via the -hash option of the openssl x509 command. See the OpenSSL documentation
  # for more information.
  #:ssl_ca_path: '/path/to/ca'

  # Turn SSL verification on/off
  #:verify_ssl: true

  # Path to a client certificate, DER- or PEM-encoded certificates are supported
  #:ssl_client_cert: '/path/to/cert.crt'

  # Path to a client key
  #:ssl_client_key: '/path/to/cert.key'

  # Enable standard authentication in addition to client certificate authentication.
  # Switch to false if you want to rely on certificates only.
  #:ssl_with_basic_auth: true

  # Local CA cert store path where hammer stores certificates fetched from the server.
  # Certs from the local storage are used only when neither :ssl_ca_file: nor :ssl_ca_path: is cofigured.
  #:local_ca_store_path: '~/.hammer/certs'
