:modules:
#    - hammer_cli_foreman
#    - hammer_cli_katello

:foreman:
  :host: 'https://localhost/'
  :username: 'admin'
  :password: 'changeme'

# :watch_plain: true disables color output of logger.watch in Clamp commands
:watch_plain: false


#:log_dir: '/var/log/foreman'
:log_dir: '~/.foreman/log'
:log_level: 'error'
:log_api_calls: false
