# User interface related settings
:ui:
  # Enable interactive queries?
  :interactive: true
  # Number of records listed per page
  # :per_page: 20
  # Location of shell history file
  :history_file: '~/.hammer/history'
  # Mark translated strings with X characters (for developers)
  #:mark_translated: false


# Enable/disable color output of logger in Clamp commands
:watch_plain: false

# Forece relaod of Apipie cache with every Hammer invocation
:reload_cache: false

# Directory where the logs are stored. The default is /var/log/hammer/ and the log file is named hammer.log
:log_dir: '~/.hammer/log'

# Logging level. One of debug, info, warning, error, fatal
:log_level: 'error'

#:log_owner: 'foreman'
#:log_group: 'foreman'

# Maximum log size in bytes. Log rotates when the value gets exceeded
#:log_size: 5 #in MB

# Log record pattern (logging gem syntax)
#:log_pattern: '[%5l %d %c] %m'


# SSL auth options
#:ssl:
  # Path to a ca file
  #:ssl_ca_file: '/path/to/ca_certificate.pem'

  # Path to a direcotry with ca file
  #:ssl_ca_path: '/path/to/ca/'

  # Turn SSL verification on/off
  #:verify_ssl: true

  # Path to a client certificate
  #:ssl_client_cert: '/path/to/cert.crt'

  # Path to a client key
  #:ssl_client_key: '/path/to/cert.key'

  # Enable standard authentication in addition to client certificate authentication
  #:auth_with_client_cert: true
